ffmpeg: include <libavutil/mathematics.h>
The libav project is not including the header in libavutil/avutil.h
anymore (commit 0ebcdf5cdad6bf20a5170735a7f77b23ecc081ac).

ffmpeg.c:406:2: error: implicit declaration of function 'av_rescale_q' [-Werror=implicit-function-declaration]