Fix mp4 compile error with SVN versions
The reason is that the MP4 API changed, but it only affects C, not C++,
since only default parameters were changed.

SVN entry that changed MP4Close(): r479
SVN entry that changed MP4Read(): r453

They only reliable check seems to be introduced/dropped #defines :-(

mp4.c: In function 'mp4_open':
mp4.c:159:2: error: too many arguments to function 'MP4Read'
/usr/include/mp4v2/file.h:331:15: note: declared here
mp4.c:208:3: error: too few arguments to function 'MP4Close'
/usr/include/mp4v2/file.h:56:6: note: declared here
mp4.c: In function 'mp4_close':
mp4.c:222:3: error: too few arguments to function 'MP4Close'
/usr/include/mp4v2/file.h:56:6: note: declared here

Reported-by: Anonymous user